#ifndef __MultiViewerTableNameSelectDlg__
#define __MultiViewerTableNameSelectDlg__

/**
@file
Subclass of TableNameSelectDlg, which is generated by wxFormBuilder.
*/

#include "MainFrame.h"

/** Implementing TableNameSelectDlg */
class MultiViewerTableNameSelectDlg : public TableNameSelectDlg
{
protected:
	// Handlers for TableNameSelectDlg events.
	void OnCancelButtonClick( wxCommandEvent& event );
	void OnOKButtonClick( wxCommandEvent& event );
	
public:
	/** Constructor */
	MultiViewerTableNameSelectDlg( wxWindow* parent );

	void AddTableName(wxString a_wxStrTableName);
	void SetDefault();
	int GetSelectTableNumber();
};

#endif // __MultiViewerTableNameSelectDlg__
